# site
markdown: kramdown 				# markdown parser(or rdiscount)
permalink: /:categories/:title/	            # change default url
safe: true         				# safe mode
# paginate: 50					# number of posts on homepage
truncate: 200 				# the number of words preview a post

# peronal
name: Shaw			# site f
author: Shaw					# author
url: https://xiaojunjie.github.io			# url
description: 肖俊杰的博客 		# description
keywords: 肖俊杰，西电，罗源
# storage: http://static.xjjfly.com/
storage:

# socail
email: admin@xjjfly.com
qq_id: 971308896
sinaweibo_id: 971308896
github_username: xiaojunjie   	# github.com
zhihu: xiaojunjie
facebook: junjie.xiao.50
twitter: JunJieShaw
googleplus: 116422405935714641713

# plugin
highlighter: rouge



# default
defaults:
  -
    scope:
      path: "" # 一个空的字符串代表项目中所有的文件
      type: "posts"
    values:
      layout: "post"

exclude: [node_modules]

# backup
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
layouts_dir:     ./_layouts
destination: ./_site
encoding:     "utf-8"
